Fix, to allow batchDelete
Hi,
Batch delete was causing a 
``
FatalErrorException: Error: Cannot use object of type Application\Sonata\MediaBundle\Document\Media as array
``
before this.
Thanks !